project:
  type: website

website:
  title: "Bede Ffinian Rowe Davies"
  description: "Marine Ecologist and Statistician bedeffinian@gmail.com"
  site-url: https://www.bedeffinianrowedavies.com
  favicon: Images/index/whale.ico
  open-graph: true
  twitter-card:
    creator: "@bedeffinian" 
  page-navigation: true
  navbar:
   pinned: true
   background: "#008b8b"
   foreground: "#dbb13b"
   search: true
   logo: Images/index/whale.ico
   right:
    - text: "Home"
      file: index.qmd
    - text: "Consultancy"
      file: consultancy.qmd
    - text: "Projects"
      file: map.qmd
    - text: "Publications"
      file: Publications.qmd
    - text: "Blogs"
      file: Blogs.qmd
    - text: "Tutorials"
      file: Tutorials.qmd
    - icon: github
      href: https://github.com/bedeffinian
    - icon: twitter
      href: https://twitter.com/bedeffinian
    - icon: flower2
      href: https://orcid.org/0000-0001-6462-4347
    - icon: file-bar-graph
  page-footer: 
    left:
      - icon: github
        href: https://github.com/bedeffinian/bedeffinianrowedavies
    center: |
      <span> **Bede Ffinian Rowe Davies**<br> Post-Doctoral Researcher in Marine Ecology and Statistics [bedeffinian@gmail.com](bedeffinian@gmail.com)<br> 
      [Laboratoire ISOMer, UFR Sciences et Techniques](https://isomer.univ-nantes.fr/rsbe-remote-sensing-benthic-ecology)<br>
      [Nantes University](https://english.univ-nantes.fr/), France.</span>
    right: |
      <span> Built with <a href="https://quarto.org/">Quarto</a></span>
    border: true
    foreground: "#dbb13b"
    background: "#467373"
  sidebar:
      contents: 
        - section: "Who am I and What have I done?" 
          contents: 
            - index.qmd
            - map.qmd
            - Publications.qmd
        - text: "---" 
        - section: "Consultancy Work"
          contents:
            - consultancy.qmd
        - text: "---"
        - section: "Basic R Tutorials"
          contents: 
            - BasicRTutorials/IntroductionR.qmd
            - BasicRTutorials/DataManipulation.qmd
            - BasicRTutorials/DataVisualisation.qmd
        - text: "---"
        - section: "Intermediate R Tutorials"
          contents: 
            - IntermediateRTutorials/CombiningPlots.qmd
            - IntermediateRTutorials/StarterGIS.qmd
            - IntermediateRTutorials/MakingMaps.qmd
            - IntermediateRTutorials/MakingInteractiveMaps.qmd
            - IntermediateRTutorials/ComplexGIS.qmd
        - text: "---"
        - section: "General Linear Models Tutorials"
          contents:
            - StatisticsTutorials/IntroductionGLMs.qmd
            - StatisticsTutorials/GaussianGLMs.qmd
            - StatisticsTutorials/PoissonGLMs.qmd
            - StatisticsTutorials/BinomialGLMs.qmd
            - StatisticsTutorials/GammaGLMs.qmd
            - StatisticsTutorials/BetaGLMs.qmd
            - StatisticsTutorials/ProblematicGLMs.qmd
            - StatisticsTutorials/ZeroInflatedGLMs.qmd
        - text: "---"
        - section: "Mixed Effects Models Tutorials"
          contents:
            - StatisticsTutorialsGLMM/IntroductionGLMMs.qmd
        - text: "---"
        - section: "Machine Learning Tutorials"
          contents:
            - StatisticsMLTutorials/IntroMachineLearning.qmd
            - StatisticsMLTutorials/ComparingMLs.qmd
      collapse-level: 1
      foreground: "#dbb13b"
      background: "#467373"
       
format:
  html:
    toc: true
    toc-location: left
    theme:
      dark: CustomStyle_Dark.scss
      light: CustomStyle_Light.scss
      

editor: source

