project:
  type: website

website:
  title: "Bede Ffinian Rowe Davies Consultancy"
  description: "Ecology and Statistical Consultant bedeffinian@gmail.com"
  site-url: "https://BedeFfinianRoweDavies_Consultancy.com"
  navbar:
   background: "#008b8b"
   foreground: "#dbb13b"
   search: true
   right:
    - text: "Home"
      href: who.qmd
    - text: "Consultancy"
      href: index.qmd
    - text: "Previous Projects"
      href: map.qmd
    - text: "First Author Publications"
      href: Posts1.qmd
    - text: "Co-Author Publications"
      href: Posts2.qmd
    - icon: github
      href: https://github.com/bedeffinian
    - icon: twitter
      href: https://twitter.com/bedeffinian

format:
  html:
    theme: spacelab
    css: styles.css

editor: source

