project:
  type: website

website:
  title: "Bede Ffinian Rowe Davies"
  description: "Marine Ecologist and Statistician bedeffinian@gmail.com"
  site-url: "BedeFfinianRoweDavies.com"
  navbar:
   background: "#008b8b"
   foreground: "#dbb13b"
   search: true
   right:
    - text: "Home"
      href: index.qmd
    - text: "Consultancy"
      href: consultancy.qmd
    - text: "Projects"
      href: map.qmd
    - text: "Publications"
      href: Posts3.qmd
    - icon: github
      href: https://github.com/bedeffinian
    - icon: twitter
      href: https://twitter.com/bedeffinian
    - icon: flower
      href: https://orcid.org/my-orcid?orcid=0000-0001-6462-4347

format:
  html:
    theme: spacelab
    css: styles.css

editor: source

