---
title: "Acoustic Complexity Index to Assess Benthic Biodiversity of a Partially Protected Area in the Southwest of the UK"
description: |
  Bede F.R. Davies, Martin J. Attrill, Luke Holmes, Adam Rees, Matthew J. Witt & Emma V. Sheehan.
author:
  - name: Bede Ffinian Rowe Davies
preview: Acoustics_Preview.png
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Davies *et al.,* 2020](http://publicationslist.org/data/m.j.witt/ref-126/Davies_2020_EcolIndicators.pdf)

The soundscape of the marine environment is a relatively understudied area of ecology that has the potential to provide large amounts of information on biodiversity, reproductive behaviour, habitat selection, spawning and predator–prey interactions. Biodiversity is often visually assessed and used as a proxy for ecosystem health. Visual assessment using divers or remote video methods can be expensive, and limited to times of good weather and water visibility. Previous studies have concluded that acoustic measures, such as the Acoustic Complexity Index (ACI), correlate with visual biodiversity estimates and offer an alternative to assess ecosystem health. Here, the ACI measured over 5 years in a Marine Protected Area (MPA) in the UK, Lyme Bay, was analysed alongside another monitoring method, Baited Remote Underwater Video Systems (BRUVs). Two treatments were sampled annually in the summer from 2014 until 2018 with sites inside the MPA, as well as Open Control sites outside of the MPA. Year by year correlations, which have been used elsewhere to test ACI, showed significant correlations with Number of Species and ACI. However, the sign of these correlations changed almost yearly, showing that more in-depth analyses are needed. Multivariate analysis of the benthic assemblage composition (from BRUVs) was carried out by Permutational Multivariate Analysis of Variance (PERMANOVA) using Distance Matrices. Although not consistently correlating with univariate measures, the ACI was significantly interacting with the changing benthic assemblage composition, as it changed over time and protection (Inside vs Outside the MPA). ACI showed potential to allude to shifting benthic communities, yet with no consistency when used alongside univariate measures of diversity. Although it is not without its own disadvantages, and thus should be developed further before implementation, the ACI could potentially reflect more complex changes to the benthos than simply the overall diversity.
